repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.0
  hooks:
    - id: gitleaks
      name: " security 路 Detect hardcoded secrets"

- repo: https://github.com/hukkin/mdformat
  rev: 1.0.0
  hooks:
    - id: mdformat
      name: " markdown 路 Format markdown"
      additional_dependencies:
      - mdformat-front-matters

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-merge-conflict
      name: " git 路 Detect conflict markers"
    - id: forbid-new-submodules
      name: " git 路 Prevent submodule creation"
    - id: check-added-large-files
      name: " git 路 Block large file commits"
      args: ['--maxkb=5000']
    - id: end-of-file-fixer
      name: " markdown 路 Fix end of file"
    - id: mixed-line-ending
      name: " markdown 路 Fix end of lines"
      args: ['--fix=lf']
    - id: trailing-whitespace
      name: " markdown 路 Fix trailing whitespace"
      args: ['--markdown-linebreak-ext=md']
